### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/coloring-book-gallery#4]
It should be clear what the license of this repository is.

**Comment by vazhnov** [comment]
Thank you for a nice program with opensource pictures!
Any update in this issue?

**Comment by niccokunzmann** [comment]
The pictures all have a license. I wonder which license I can use for the repository. I think, it would be CC-BY-SA, then. At the moment I am on thr phone. I can review pull requests but it is hard to add the text.
Would you add CC-BY-SA in the necessary places (Readme and license files), noting that the pictures have other licenses?
